# Generated by Django 2.0.5 on 2018-05-23 17:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('population', models.IntegerField(null=True)),
                ('area', models.FloatField(null=True)),
                ('cars_pp', models.FloatField(null=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('population', models.IntegerField(null=True)),
                ('area', models.FloatField(null=True)),
                ('cars_pp', models.FloatField(null=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='cars_pp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='canton',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.City'),
        ),
        migrations.AddField(
            model_name='canton',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.Country'),
        ),
    ]
