# Generated by Django 2.0.5 on 2018-05-24 11:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20180524_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='city',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='country',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326),
        ),
    ]
