# Generated by Django 2.0.5 on 2018-05-24 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20180524_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='city',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='country',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
    ]
