# Generated by Django 2.0.5 on 2018-05-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20180524_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('tree_density', models.FloatField()),
                ('tree_sparsity', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='has_mapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='tree_density',
            field=models.FloatField(null=True),
        ),
    ]
