# Generated by Django 2.0.5 on 2018-05-25 09:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_auto_20180525_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
    ]
