# Generated by Django 2.0.5 on 2018-05-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_tile_mpoly'),
    ]

    operations = [
        migrations.AddField(
            model_name='canton',
            name='has_mapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canton',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='canton',
            name='tree_density',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='has_mapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='tree_density',
            field=models.FloatField(null=True),
        ),
    ]
