# Generated by Django 2.0.5 on 2018-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20180525_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
