# Generated by Django 2.0.5 on 2018-05-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_tile_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='tree_sparsity',
            field=models.FloatField(null=True),
        ),
    ]
