# Generated by Django 2.0.5 on 2018-05-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_city_tree_sparsity'),
    ]

    operations = [
        migrations.AddField(
            model_name='canton',
            name='tree_sparsity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='tree_sparsity',
            field=models.FloatField(null=True),
        ),
    ]
